version: '2'
services:
  octoeverywhere-bambu-connect:
    image: octoeverywhere/octoeverywhere:latest
    environment:
        # https://octoeverywhere.com/s/access-code
      - ACCESS_CODE=XXXXXXXX
        # https://octoeverywhere.com/s/bambu-sn
      - SERIAL_NUMBER=XXXXXXXXXXXXXXX
        # Find using the printer's display
      - PRINTER_IP=192.168.1.1
    volumes:
      # Specify a path mapping for the required persistent storage
      - /some/path/on/your/computer:/data

  # Add as many printers as you want!
  # octoeverywhere-bambu-connect-2:
  #   image: octoeverywhere/octoeverywhere:latest
  #   environment:
  #       # https://octoeverywhere.com/s/access-code
  #     - ACCESS_CODE=XXXXXXXX
  #       # https://octoeverywhere.com/s/bambu-sn
  #     - SERIAL_NUMBER=XXXXXXXXXXXXXXX
  #       # Find using the printer's display
  #     - PRINTER_IP=192.168.1.2
  #   volumes:
  #     # Specify a path mapping for the required persistent storage
  #     - /some/path/on/your/computer/printer2:/data