version: '2'
services:
  octoeverywhere-bambu-connect:
    image: octoeverywhere/octoeverywhere:latest
    environment:
        # https://octoeverywhere.com/s/access-code
      - ACCESS_CODE=XXXXXXXX
        # https://octoeverywhere.com/s/bambu-sn
      - SERIAL_NUMBER=XXXXXXXXXXXXXXX
        # Find using the printer's display or use https://octoeverywhere.com/s/bambu-ip
      - PRINTER_IP=XXX.XXX.XXX.XXX
    volumes:
      # This can also be an absolue path, e.g. /var/octoeverywhere/plugin/data or /c/users/name/plugin/data
      - ./data:/data

  # Add as many printers as you want!
  # octoeverywhere-bambu-connect-2:
  #   image: octoeverywhere/octoeverywhere:latest
  #   environment:
  #       # https://octoeverywhere.com/s/access-code
  #     - ACCESS_CODE=XXXXXXXX
  #       # https://octoeverywhere.com/s/bambu-sn
  #     - SERIAL_NUMBER=XXXXXXXXXXXXXXX
  #       # Find using the printer's display or use https://octoeverywhere.com/s/bambu-ip
  #     - PRINTER_IP=XXX.XXX.XXX.XXX
  #   volumes:
  #     # Specify a path mapping for the required persistent storage
  #     - ./data:/data