# def write_error_codes_to_file():
#     import requests
#     result = requests.get("https://e.bambulab.com/query.php?lang=en")
#     if result.status_code != 200:
#         print("Failed to fetch error codes")
#         return
#     error_codes = result.json().get("data", {}).get("device_error", {}).get("en", [])
#     if not error_codes or len(error_codes) == 0:
#         print("No error codes found")
#         return
#     with open("c:/Users/quinn/Desktop/bambu_error_codes.py", "w", encoding="utf-8") as f:
#         f.write("BAMBU_PRINT_ERROR_STRINGS = {\n")
#         for item in error_codes:
#             ecode = item["ecode"]
#             intro = item["intro"].replace('"', '\\"')  # Escape double quotes in the intro text
#             f.write(f'    "{ecode}": "{intro}",\n')
#         f.write("}\n")
#     print("done!")
# write_error_codes_to_file()
#
BAMBU_PRINT_ERROR_STRINGS = {
    "07038012": "Failed to get AMS mapping table; please select \"Resume\" to retry.",
    "07058011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "07004001": "The AMS has been disabled for a print, but it still has filament loaded. Please unload the AMS filament and switch to the spool holder filament for printing.",
    "07FF8003": "Please pull out the filament on the spool holder. If this message persists, please check to see if there is filament broken in the extruder. (Connect a PTFE tube if you are about to use an AMS.)",
    "03004000": "Z axis homing failed; the task has been stopped.",
    "07018013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "07FF8001": "Failed to cut the filament. Please check the cutter.",
    "0300800B": "The cutter is stuck. Please make sure the cutter handle is out and check the filament sensor cable connection.",
    "1802C06B": "AMS-HT C is changing filament. Unable to start drying. Please try again later.",
    "18078005": "The AMS-HT failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "07048003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "0500400E": "Printing was cancelled.",
    "0500403F": "Failed to download print job; please check your network connection.",
    "05004006": "There is not enough free storage space for the print job. Restoring to factory settings can free up available space.",
    "0501401E": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "05004003": "Printing stopped because the printer was unable to parse the file. Please resend your print job.",
    "05014034": "The slicing progress has not been updated for a long time, and the printing task has exited. Please confirm the parameters and reinitiate printing.",
    "18028007": "Extruding filament failed. The extruder might be clogged.",
    "18038012": "Failed to get AMS mapping table; please select \"Resume\" to retry.",
    "0300400C": "The task was canceled.",
    "03008018": "Chamber temperature malfunction.",
    "07058016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "05004002": "Unsupported print file path or name. Please resend the print job.",
    "07078016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "05014021": "Cloud access failed, which may be caused by network instability due to interference. You can try moving the printer closer to the router before you try again.",
    "1806C06E": "AMS-HT G motor is performing self-test. Unable to start drying. Please try again later.",
    "1800C069": "An error occurred during AMS-HT A drying. Please go to Assistant for more details.",
    "1804C06A": "AMS-HT E is reading RFID. Unable to start drying. Please try again later.",
    "1807C06C": "AMS-HT H is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "03004002": "Auto Bed Leveling failed; the task has been stopped.",
    "1803C069": "An error occurred during AMS-HT D drying. Please go to Assistant for more details.",
    "0500401D": "Cloud access failed, which may be caused by network instability due to interference. You can try moving the printer closer to the router before you try again.",
    "0703C06D": "AMS D is assisting in filament insertion. Unable to start drying. Please try again later.",
    "05004040": "The printer has reached its power limit. Please connect a dedicated power adapter to this AMS to enable drying.",
    "18018023": "AMS-HT B cooling failed. The ambient temperature may be too high. Please operate the device in a suitable environment.",
    "0300400A": "Mechanical resonance frequency identification failed.",
    "05004041": "The AMS drying cannot be started during printing.",
    "18008012": "Failed to get AMS mapping table; please select \"Resume\" to retry.",
    "18048016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "18038010": "The AMS-HT assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "0501401C": "Cloud access is rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "07068004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "07028001": "Failed to cut the filament. Please check the cutter.",
    "07008010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "18078016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "18028012": "Failed to get AMS mapping table; please select \"Resume\" to retry.",
    "05004027": "Cloud access failed; this may be caused by network instability due to interference. You can try moving the printer closer to the router before you try again.",
    "07FFC009": "Please feed filament into the PTFE tube until it can not be pushed any farther.",
    "18018004": "AMS-HT failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "07018017": "AMS B is drying. Please stop drying process before loading/unloading material.",
    "07038010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "1802C06C": "AMS-HT C is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "05004025": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "05008036": "Your sliced file is not consistent with the current printer model. Continue?",
    "07038001": "Failed to cut the filament. Please check the cutter.",
    "18044025": "Failed to read the filament information.",
    "03008011": "Detected build plate is not the same as the Gcode file. Please adjust slicer settings or use the correct plate.",
    "1803C06C": "AMS-HT D is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "1806C06D": "AMS-HT G is assisting in filament insertion. Unable to start drying. Please try again later.",
    "05004023": "Cloud access rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "05008030": "",
    "0501401D": "Cloud access failed, which may be caused by network instability due to interference. You can try moving the printer closer to the router before you try again.",
    "0501401B": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "07028013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "18008017": "AMS-HT A is drying. Please stop drying process before loading/unloading material.",
    "07058012": "Failed to get AMS mapping table; please select \"Resume\" to retry.",
    "07014001": "Filament is still loaded from the AMS after it has been disabled. Please unload the filament, load from the spool holder, and restart printing.",
    "18058004": "AMS-HT failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "0701C069": "An error occurred during AMS B drying. Please go to Assistant for more details.",
    "05004026": "Cloud access rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "1801C06C": "AMS-HT B is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "07008007": "Extruding filament failed. The extruder might be clogged.",
    "07FF8005": "Failed to feed the filament outside the AMS. Please clip the end of the filament flat and check to see if the spool is stuck.",
    "18008007": "Extruding filament failed. The extruder might be clogged.",
    "0702C06E": "AMS C motor is performing self-test. Unable to start drying. Please try again later.",
    "07FFC008": "Please pull out the filament on the spool holder. If this message persists, please check to see if there is filament broken in the extruder. (Connect a PTFE tube if you are about to use an AMS)",
    "07028007": "Extruding filament failed. The extruder might be clogged.",
    "0500400A": "The file name is not supported. Please rename and restart the print job.",
    "07048004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "0700C06D": "AMS A is assisting in filament insertion. Unable to start drying. Please try again later.",
    "0C00402C": "Device data link error. Please reboot the printer.",
    "18008004": "AMS-HT failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "03008005": "Toolhead front cover fell off. Please remount the front cover and check to make sure your print is going okay.",
    "07048023": "AMS E cooling failed. The ambient temperature may be too high. Please operate the device in a suitable environment.",
    "1802C06A": "AMS-HT C is reading RFID. Unable to start drying. Please try again later.",
    "05004007": "The device requires a repair upgrade, and printing is currently unavailable.",
    "07018010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "1804C06E": "AMS-HT E motor is performing self-test. Unable to start drying. Please try again later.",
    "07058007": "Extruding filament failed. The extruder might be clogged.",
    "07058010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "07028016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "18078011": "AMS-HT filament ran out. Please insert a new filament into the same AMS-HT slot.",
    "07FF8004": "Failed to pull back the filament from the toolhead to AMS. Please check whether the filament or the spool is stuck.",
    "07068011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "07FF8011": "External filament has run out; please load a new filament.",
    "0500401C": "Cloud access is rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "05004031": "The accessory firmware does not match the printer. Please upgrade it on the \"Firmware\" page.",
    "18008003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "03008010": "The hotend cooling fan speed is abnormal.",
    "18058003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "07024001": "Filament is still loaded from the AMS after it has been disabled. Please unload the filament, load from the spool holder, and restart printing.",
    "18048005": "The AMS-HT failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "0702C06C": "AMS C is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "10014001": "Timelapse is not supported as Spiral Vase mode is enabled in slicing presets.",
    "0702C06B": "AMS C is changing filament. Unable to start drying. Please try again later.",
    "18058016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "07038023": "AMS D cooling failed. The ambient temperature may be too high. Please operate the device in a suitable environment.",
    "07068003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "18064025": "Failed to read the filament information.",
    "07048010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "18078012": "Failed to get AMS mapping table; please select \"Resume\" to retry.",
    "18048023": "AMS-HT E cooling failed. The ambient temperature may be too high. Please operate the device in a suitable environment.",
    "0500C011": "",
    "03008003": "Spaghetti defects were detected by the AI Print Monitoring. Please check the quality of the printed model before continuing your print. Cleaning the build plate or drying the filament can effectively reduce the risk of spaghetti failure.",
    "18048010": "The AMS-HT assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "1803C06A": "AMS-HT D is reading RFID. Unable to start drying. Please try again later.",
    "18018016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "18068012": "Failed to get AMS mapping table; please select \"Resume\" to retry.",
    "0500402A": "Failed to connect to the router, which may be caused by wireless interference or being too far away from the router. Please try again or move the printer closer to the router and try again.",
    "07018012": "Failed to get AMS mapping table; please select \"Resume\" to retry.",
    "07018005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "18008010": "The AMS-HT assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "07078011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "05014039": "Device login has expired; please try to bind again.",
    "0500401E": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "18038003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "0703C069": "An error occurred during AMS D drying. Please go to Assistant for more details.",
    "07008023": "AMS A cooling failed. The ambient temperature may be too high. Please operate the device in a suitable environment.",
    "0701C06C": "AMS B is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "0702C069": "An error occurred during AMS C drying. Please go to Assistant for more details.",
    "07058023": "AMS F cooling failed. The ambient temperature may be too high. Please operate the device in a suitable environment.",
    "18058011": "AMS-HT filament ran out. Please insert a new filament into the same AMS-HT slot.",
    "03008006": "The build plate marker was not detected. Please confirm the build plate is correctly positioned on the heatbed with all four corners aligned, and the marker is visible.",
    "05014032": "QR code binding is in progress, so device discovery binding cannot be performed. You can scan the QR code on the screen for binding or exit the QR code display page on screen and try device discovery binding.",
    "18018007": "Extruding filament failed. The extruder might be clogged.",
    "07008017": "AMS A is drying. Please stop drying process before loading/unloading material.",
    "18038004": "AMS-HT failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "0500402B": "Router connection failed due to incorrect password. Please check the password and try again.",
    "18028023": "AMS-HT C cooling failed. The ambient temperature may be too high. Please operate the device in a suitable environment.",
    "07028017": "AMS C is drying. Please stop drying process before loading/unloading material.",
    "05014023": "Cloud access rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "07018003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "07038004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "1803C06B": "AMS-HT D is changing filament. Unable to start drying. Please try again later.",
    "05004004": "Device is busy and cannot start new task. Please wait for current task to complete before sending new task.",
    "03008017": "Foreign objects detected on heatbed. Please check and clean the heatbed. Then, select \"Resume\" to resume the print job.",
    "07048007": "Extruding filament failed. The extruder might be clogged.",
    "05014038": "The regional settings do not match the printer; please check the printer's regional settings.",
    "07024025": "Failed to read the filament information.",
    "07FF8002": "The cutter is stuck. Please make sure the cutter handle is out.",
    "07008003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "05004037": "Your sliced file is not compatible with current printer model. This file can't be printed on this printer.",
    "07058003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "18038011": "AMS-HT filament ran out. Please insert a new filament into the same AMS-HT slot.",
    "05014027": "Cloud access failed; this may be caused by network instability due to interference. You can try moving the printer closer to the router before you try again.",
    "07004025": "Failed to read the filament information.",
    "07038011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "18008023": "AMS-HT A cooling failed. The ambient temperature may be too high. Please operate the device in a suitable environment.",
    "05004043": "Due to power limitations, only one AMS is allowed to use the device's power for drying.",
    "07028011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "1800C06A": "AMS-HT A is reading RFID. Unable to start drying. Please try again later.",
    "05014019": "The printer has already been bound. Please unbind it and try again.",
    "1807C06B": "AMS-HT H is changing filament. Unable to start drying. Please try again later.",
    "0300800D": "Detected that the extruder is not extruding normally. If the defects are acceptable, select \"Resume\" to resume the print job.",
    "07FF8007": "Please observe the nozzle. If the filament has been extruded, select \"Done\"; if not, please push the filament forward slightly, and then select \"Retry\".",
    "07FF8012": "Failed to get AMS mapping table; please select \"Resume\" to retry.",
    "1806C06A": "AMS-HT G is reading RFID. Unable to start drying. Please try again later.",
    "03004005": "The hotend cooling fan speed is abnormal.",
    "18018011": "AMS-HT filament ran out. Please insert a new filament into the same AMS-HT slot.",
    "03008008": "Nozzle temperature malfunction",
    "0701C06B": "AMS B is changing filament. Unable to start drying. Please try again later.",
    "0700C06B": "AMS A is changing filament. Unable to start drying. Please try again later.",
    "07008011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "10018003": "The time-lapse mode is set to Traditional in the slicing file. This may cause surface defects. Would you like to enable it?",
    "07038007": "Extruding filament failed. The extruder might be clogged.",
    "03008019": "Build plate not detected. Please ensure there are no bulges or debris on the plate and that the nozzle is clean.",
    "05004033": "The AMS firmware does not match the printer. Please upgrade it on the \"Firmware\" page.",
    "0500402C": "Failed to obtain IP address, which may be caused by wireless interference resulting in data transmission failure or the DHCP address pool of the router being full. Please move the printer closer to the router and try again. If the issue persists, please check router settings to see whether the IP addresses have been exhausted.",
    "1801C06D": "AMS-HT B is assisting in filament insertion. Unable to start drying. Please try again later.",
    "18028003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "03008013": "Printing paused due to the pause command added to the printing file.",
    "18008011": "AMS-HT filament ran out. Please insert a new filament into the same AMS-HT slot.",
    "07034025": "Failed to read the filament information.",
    "03004066": "Calibration of motion precision failed.",
    "18008016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "07068005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "03004013": "Printing cannot be initiated while AMS is drying.",
    "05004021": "Cloud access failed, which may be caused by network instability due to interference. You can try moving the printer closer to the router before you try again.",
    "07FFC003": "Please pull out the filament on the spool holder. If this message persists, please check to see if there is filament broken in the extruder or PTFE tube. (Connect a PTFE tube if you are about to use an AMS)",
    "07028010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "05014017": "Binding failed. Please retry or restart the printer and retry.",
    "03008002": "First layer defects were detected by the Micro Lidar. Please check the quality of the printed model before continuing your print.",
    "07008004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "18054025": "Failed to read the filament information.",
    "05004009": "Print jobs are not allowed to be sent while updating logs.",
    "05014026": "Cloud access rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "18038017": "AMS-HT D is drying. Please stop drying process before loading/unloading material.",
    "07FF4001": "Filament is still loaded from the AMS after it has been disabled. Please unload the filament, load from the spool holder, and restart printing.",
    "05004005": "Print jobs are not allowed to be sent while updating firmware.",
    "0500400B": "There was a problem downloading a file. Please check your network connection and resend the print job.",
    "07048016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "07068023": "AMS G cooling failed. The ambient temperature may be too high. Please operate the device in a suitable environment.",
    "07018016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "18018012": "Failed to get AMS mapping table; please select \"Resume\" to retry.",
    "07038016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "18068005": "The AMS-HT failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "0701C06E": "AMS B motor is performing self-test. Unable to start drying. Please try again later.",
    "05004001": "Failed to connect to Bambu Cloud. Please check your network connection.",
    "0702C06D": "AMS C is assisting in filament insertion. Unable to start drying. Please try again later.",
    "18018017": "AMS-HT B is drying. Please stop drying process before loading/unloading material.",
    "07018011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "05004022": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "1801C069": "An error occurred during AMS-HT B drying. Please go to Assistant for more details.",
    "07078003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "18028017": "AMS-HT C is drying. Please stop drying process before loading/unloading material.",
    "18FF8005": "Failed to feed the filament outside the AMS-HT. Please clip the end of the filament flat and check to see if the spool is stuck.",
    "07074025": "Failed to read the filament information.",
    "18048012": "Failed to get AMS mapping table; please select \"Resume\" to retry.",
    "05014035": "The device is in the process of binding and cannot respond to new binding requests.",
    "07028002": "The cutter is stuck. Please make sure the cutter handle is out.",
    "07028012": "Failed to get AMS mapping table; please select \"Resume\" to retry.",
    "18048011": "AMS-HT filament ran out. Please insert a new filament into the same AMS-HT slot.",
    "1800C06C": "AMS-HT A is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "10014002": "Timelapse is not supported as the Print sequence is set to \"By object\".",
    "18068023": "AMS-HT G cooling failed. The ambient temperature may be too high. Please operate the device in a suitable environment.",
    "18048004": "AMS-HT failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "0700C069": "An error occurred during AMS A drying. Please go to Assistant for more details.",
    "0300400D": "Resume failed after power loss.",
    "03008009": "Heatbed temperature malfunction",
    "18048007": "Extruding filament failed. The extruder might be clogged.",
    "05004019": "The printer has already been bound. Please unbind it and try again.",
    "07028004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "05004016": "The MicroSD Card is write-protected. Please replace the MicroSD Card.",
    "05004029": "Cloud access is rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "07058005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "07018007": "Extruding filament failed. The extruder might be clogged.",
    "07078007": "Extruding filament failed. The extruder might be clogged.",
    "18058005": "The AMS-HT failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "0C00C004": "Possible spaghetti failure was detected. Cleaning the build plate or drying the filament can effectively reduce the risk of spaghetti failure.",
    "05024001": "Current filament will be used in this print job. Settings cannot be changed.",
    "07068007": "Extruding filament failed. The extruder might be clogged.",
    "18038023": "AMS-HT D cooling failed. The ambient temperature may be too high. Please operate the device in a suitable environment.",
    "18068016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "18FF8012": "Failed to get AMS mapping table; please select \"Resume\" to retry.",
    "18068004": "AMS-HT failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "05004038": "The nozzle diameter in sliced file is not consistent with the current nozzle setting. This file can't be printed.",
    "07038002": "The cutter is stuck. Please make sure the cutter handle is out.",
    "05014029": "Cloud access is rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "0C00C003": "Possible defects were detected in the first layer.",
    "0703C06C": "AMS D is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "03008014": "The nozzle is covered with filament, or the build plate is installed incorrectly. Please cancel this print and clean the nozzle or adjust the build plate according to the actual status. You can also select \"Resume\" to resume the print job.",
    "05004028": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "07048011": "AMS filament ran out. Please insert a new filament into the same AMS slot.",
    "05014028": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "07078010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "1806C06C": "AMS-HT G is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "07044025": "Failed to read the filament information.",
    "07028023": "AMS C cooling failed. The ambient temperature may be too high. Please operate the device in a suitable environment.",
    "18058010": "The AMS-HT assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "05004024": "Cloud access failed. Possible reasons include network instability caused by interference, inability to access the internet, or router firewall configuration restrictions. You can try moving the printer closer to the router or checking the router configuration before you try again.",
    "0500400D": "Please run a self-test and restart the print job.",
    "0701C06A": "AMS B is reading RFID. Unable to start drying. Please try again later.",
    "05024004": "Some features are not supported by the current device. Please check the Studio feature settings or update the firmware to the latest version.",
    "0300800F": "The door seems to be open, so printing was paused.",
    "07018001": "Failed to cut the filament. Please check the cutter.",
    "03008001": "Printing was paused by the user. You can select \"Resume\" to continue printing.",
    "0C00C006": "Purged filament may have piled up in the waste chute.",
    "0C008002": "",
    "1802C069": "An error occurred during AMS-HT C drying. Please go to Assistant for more details.",
    "07008001": "Failed to cut the filament. Please check the cutter.",
    "07008016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "0700C06E": "AMS A motor is performing self-test. Unable to start drying. Please try again later.",
    "0501401F": "Authorization timed out. Please make sure that your phone or PC has access to the internet, and ensure that the Bambu Studio/Bambu Handy APP is running in the foreground during the binding operation.",
    "1807C06D": "AMS-HT H is assisting in filament insertion. Unable to start drying. Please try again later.",
    "1805C06A": "AMS-HT F is reading RFID. Unable to start drying. Please try again later.",
    "0500400C": "Please insert a MicroSD card and restart the print job.",
    "07068010": "The AMS assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "05014033": "Your APP region does not match with your printer; please download the APP in the corresponding region and register your account again.",
    "18038005": "The AMS-HT failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "07008012": "Failed to get AMS mapping table; please select \"Resume\" to retry.",
    "18028010": "The AMS-HT assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "1801C06B": "AMS-HT B is changing filament. Unable to start drying. Please try again later.",
    "1804C06B": "AMS-HT E is changing filament. Unable to start drying. Please try again later.",
    "03004067": "Calibration result is over the threshold.",
    "07048005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "18024025": "Failed to read the filament information.",
    "0500401B": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "1805C06B": "AMS-HT F is changing filament. Unable to start drying. Please try again later.",
    "1806C069": "An error occurred during AMS-HT G drying. Please go to Assistant for more details.",
    "18028004": "AMS-HT failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "07FF8010": "Check if the external filament spool or filament is stuck.",
    "03004020": "The nozzle presence detection failed. Please check the Assistant for details.",
    "0300800E": "The print file is not available. Please check to see if the storage media has been removed.",
    "05004020": "Cloud access rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "05008013": "The print file is not available. Please check to see if the storage media has been removed.",
    "03004006": "The nozzle is clogged.",
    "05004018": "Binding configuration information parsing failed; please try again.",
    "07064025": "Failed to read the filament information.",
    "18074025": "Failed to read the filament information.",
    "07028003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "0500402E": "The system does not support the file system currently used by the MicroSD card. Please replace the MicroSD card or format it to FAT32.",
    "1805C06C": "AMS-HT F is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "1802C06D": "AMS-HT C is assisting in filament insertion. Unable to start drying. Please try again later.",
    "1806C06B": "AMS-HT G is changing filament. Unable to start drying. Please try again later.",
    "1803C06D": "AMS-HT D is assisting in filament insertion. Unable to start drying. Please try again later.",
    "18058012": "Failed to get AMS mapping table; please select \"Resume\" to retry.",
    "07008002": "The cutter is stuck. Please make sure the cutter handle is out.",
    "07018023": "AMS B cooling failed. The ambient temperature may be too high. Please operate the device in a suitable environment.",
    "18058007": "Extruding filament failed. The extruder might be clogged.",
    "18068007": "Extruding filament failed. The extruder might be clogged.",
    "1807C06E": "AMS-HT H motor is performing self-test. Unable to start drying. Please try again later.",
    "18068011": "AMS-HT filament ran out. Please insert a new filament into the same AMS-HT slot.",
    "10018004": "Prime Tower is not enabled and time-lapse mode is set to Smooth in slicing file. This may cause surface defects. Would you like to enable it?",
    "0C008001": "First layer defects were detected. If the defects are acceptable, select \"Resume\" to resume the print job.",
    "03004009": "Homing XY axis failed.",
    "18038007": "Extruding filament failed. The extruder might be clogged.",
    "07018002": "The cutter is stuck. Please make sure the cutter handle is out.",
    "18014025": "Failed to read the filament information.",
    "07068016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "0300400E": "The motor self-check failed.",
    "18078004": "AMS-HT failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "1000C003": "Enabling Timelapse in traditional mode may cause defects; please activate this feature as needed.",
    "1805C06E": "AMS-HT F motor is performing self-test. Unable to start drying. Please try again later.",
    "0C008005": "Purged filament has piled up in the waste chute, which may cause a tool head collision.",
    "18078023": "AMS-HT H cooling failed. The ambient temperature may be too high. Please operate the device in a suitable environment.",
    "07FFC00A": "Please observe the nozzle. If the filament has been extruded, select \"Continue\"; if not, please push the filament forward slightly and then select \"Retry\".",
    "1804C06D": "AMS-HT E is assisting in filament insertion. Unable to start drying. Please try again later.",
    "0700C06C": "AMS A is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "03008000": "Printing was paused for unknown reason. You can select \"Resume\" to resume the print job.",
    "0500401A": "Cloud access failed. Possible reasons include network instability caused by interference, inability to access the internet, or router firewall configuration restrictions. You can try moving the printer closer to the router or checking the router configuration before trying again.",
    "0700C06A": "AMS A is reading RFID. Unable to start drying. Please try again later.",
    "18068003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "0703C06B": "AMS D is changing filament. Unable to start drying. Please try again later.",
    "05004014": "Slicing for the print job failed. Please check your settings and restart the print job.",
    "1801C06E": "AMS-HT B motor is performing self-test. Unable to start drying. Please try again later.",
    "0703C06A": "AMS D is reading RFID. Unable to start drying. Please try again later.",
    "05014024": "Cloud access failed. Possible reasons include network instability caused by interference, inability to access the internet, or router firewall configuration restrictions. You can try moving the printer closer to the router or checking the router configuration before you try again.",
    "07018004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "18028016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "07054025": "Failed to read the filament information.",
    "0C00402D": "The toolhead camera is not working properly; please reboot the device.",
    "07008005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "18058023": "AMS-HT F cooling failed. The ambient temperature may be too high. Please operate the device in a suitable environment.",
    "0701C06D": "AMS B is assisting in filament insertion. Unable to start drying. Please try again later.",
    "18078007": "Extruding filament failed. The extruder might be clogged.",
    "1800C06B": "AMS-HT A is changing filament. Unable to start drying. Please try again later.",
    "1800C06E": "AMS-HT A motor is performing self-test. Unable to start drying. Please try again later.",
    "07008013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "0C008009": "Build plate localization marker was not found.",
    "0501401A": "Cloud access failed. Possible reasons include network instability caused by interference, inability to access the internet, or router firewall configuration restrictions. You can try moving the printer closer to the router or checking the router configuration before trying again.",
    "18018010": "The AMS-HT assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "18008005": "The AMS-HT failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "03008016": "The nozzle is clogged with filament. Please cancel this print and clean the nozzle or select \"Resume\" to resume the print job.",
    "07078012": "Failed to get AMS mapping table; please select \"Resume\" to retry.",
    "05014031": "Device discovery binding is in progress, and the QR code cannot be displayed on the screen. You can wait for the binding to finish or abort the device discovery binding process in the APP/Studio and retry scanning the QR code on the screen for binding.",
    "07078005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "18018005": "The AMS-HT failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "0703C06E": "AMS D motor is performing self-test. Unable to start drying. Please try again later.",
    "03008004": "Filament ran out. Please load new filament.",
    "05004042": "Printing and calibration cannot be performed while the AMS is drying. Please stop the drying process or connect a power adapter to any AMS unit not used for the current print, then try again.",
    "05004008": "Starting printing failed; please power cycle the printer and resend the print job.",
    "07014025": "Failed to read the filament information.",
    "18034025": "Failed to read the filament information.",
    "0500C010": "MicroSD Card read/write exception: please reinsert or replace the MicroSD Card.",
    "0300800C": "Skipped step detected: auto-recover complete; please resume print and check if there are any layer shift problems.",
    "07034001": "Filament is still loaded from the AMS after it has been disabled. Please unload the filament, load from the spool holder, and restart printing.",
    "07078004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "0500402D": "System exception",
    "07078023": "AMS H cooling failed. The ambient temperature may be too high. Please operate the device in a suitable environment.",
    "0300400B": "Internal communication exception",
    "1804C06C": "AMS-HT E is in Feed Assist Mode. Unable to start drying. Please try again later.",
    "18028011": "AMS-HT filament ran out. Please insert a new filament into the same AMS-HT slot.",
    "07FFC006": "Please feed filament into the PTFE tube until it can not be pushed any farther.",
    "05014025": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "07FF8013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "07058004": "AMS failed to pull back filament. This could be due to a stuck spool or the end of the filament being stuck in the path.",
    "1805C069": "An error occurred during AMS-HT F drying. Please go to Assistant for more details.",
    "1803C06E": "AMS-HT D motor is performing self-test. Unable to start drying. Please try again later.",
    "05014022": "Cloud response is invalid. If you have tried multiple times and are still failing, please contact customer support.",
    "03004001": "The printer timed out waiting for the nozzle to cool down before homing.",
    "18068010": "The AMS-HT assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "18078003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "0500401F": "Authorization timed out. Please make sure that your phone or PC has access to the internet, and ensure that the Bambu Studio/Bambu Handy APP is running in the foreground during the binding operation.",
    "1804C069": "An error occurred during AMS-HT E drying. Please go to Assistant for more details.",
    "1802C06E": "AMS-HT C motor is performing self-test. Unable to start drying. Please try again later.",
    "07038005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "18004025": "Failed to read the filament information.",
    "1000C002": "Printing CF material with stainless steel may cause nozzle damage.",
    "18078010": "The AMS-HT assist motor is overloaded. This could be due to entangled filament or a stuck spool.",
    "0500402F": "The MicroSD card sector data is damaged. Please use the SD card repair tool to repair or format it. If it still cannot be identified, please replace the MicroSD card.",
    "07038017": "AMS D is drying. Please stop drying process before loading/unloading material.",
    "0300800A": "A Filament pile-up was detected by AI Print Monitoring. Please clean filament from the waste chute.",
    "07038013": "Timeout purging old filament: Please check if the filament is stuck or the extruder is clogged.",
    "07FF8006": "Please feed filament into the PTFE tube until it can not be pushed any farther.",
    "1801C06A": "AMS-HT B is reading RFID. Unable to start drying. Please try again later.",
    "05014018": "Binding configuration information parsing failed; please try again.",
    "07048012": "Failed to get AMS mapping table; please select \"Resume\" to retry.",
    "03004008": "The AMS failed to change filament.",
    "05004017": "Binding failed. Please retry or restart the printer and retry.",
    "1800C06D": "AMS-HT A is assisting in filament insertion. Unable to start drying. Please try again later.",
    "0702C06A": "AMS C is reading RFID. Unable to start drying. Please try again later.",
    "18028005": "The AMS-HT failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "1807C06A": "AMS-HT H is reading RFID. Unable to start drying. Please try again later.",
    "18048003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "07038003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "05014020": "Cloud access rejected. If you have tried multiple times and are still failing, please contact customer support.",
    "1807C069": "An error occurred during AMS-HT H drying. Please go to Assistant for more details.",
    "1805C06D": "AMS-HT F is assisting in filament insertion. Unable to start drying. Please try again later.",
    "1000C001": "High bed temperature may lead to filament clogging in the nozzle. You may open the chamber door.",
    "18038016": "The extruder is not extruding normally; please refer to the Assistant. After trouble shooting. If the defects are acceptable, please resume.",
    "07068012": "Failed to get AMS mapping table; please select \"Resume\" to retry.",
    "05004015": "There is not enough free storage space for the print job. Please format or clear files from the MicroSD card to free up space.",
    "18018003": "Failed to pull out the filament from the extruder. This might be caused by clogged extruder or filament broken inside the extruder.",
    "03008007": "There was an unfinished print job when the printer lost power. If the model is still adhered to the build plate, you can try resuming the print job.",
    "07028005": "The AMS failed to send out filament. You can clip the end of your filament flat, and reinsert. If this message persists, please check the PTFE tubes in AMS for any signs of wear and tear.",
    "0500409D": "The firmware of AMS A does not match the printer; the device cannot continue working. Please upgrade it on the \"Firmware\" page.",
    "0587409C": "The firmware of AMS-HT H does not match the printer; the device cannot continue working. Please upgrade it on the \"Firmware\" page.",
    "05844096": "The device cannot detect AMS-HT F. Please reconnect the AMS-HT cable or restart the printer.",
    "05824096": "The device cannot detect AMS-HT C. Please reconnect the AMS-HT cable or restart the printer.",
    "0502409D": "The firmware of AMS C does not match the printer; the device cannot continue working. Please upgrade it on the \"Firmware\" page.",
    "05864096": "The device cannot detect AMS-HT G. Please reconnect the AMS-HT cable or restart the printer.",
    "05014098": "The device cannot detect AMS B. Please reconnect the AMS cable or restart the printer.",
    "0582409C": "The firmware of AMS-HT C does not match the printer; the device cannot continue working. Please upgrade it on the \"Firmware\" page.",
    "0584409C": "The firmware of AMS-HT E does not match the printer; the device cannot continue working. Please upgrade it on the \"Firmware\" page.",
    "05854096": "The device cannot detect AMS-HT E. Please reconnect the AMS-HT cable or restart the printer.",
    "05874096": "The device cannot detect AMS-HT H. Please reconnect the AMS-HT cable or restart the printer.",
    "05834096": "The device cannot detect AMS-HT D. Please reconnect the AMS-HT cable or restart the printer.",
    "0581409C": "The firmware of AMS-HT B does not match the printer; the device cannot continue working. Please upgrade it on the \"Firmware\" page.",
    "0586409C": "The firmware of AMS-HT G does not match the printer; the device cannot continue working. Please upgrade it on the \"Firmware\" page.",
    "05814096": "The device cannot detect AMS-HT B. Please reconnect the AMS-HT cable or restart the printer.",
    "0585409C": "The firmware of AMS-HT F does not match the printer; the device cannot continue working. Please upgrade it on the \"Firmware\" page.",
    "05004098": "The device cannot detect AMS A. Please reconnect the AMS cable or restart the printer.",
    "05024098": "The device cannot detect AMS C. Please reconnect the AMS cable or restart the printer.",
    "0503409D": "The firmware of AMS D does not match the printer; the device cannot continue working. Please upgrade it on the \"Firmware\" page.",
    "0580409C": "The firmware of AMS-HT A does not match the printer; the device cannot continue working. Please upgrade it on the \"Firmware\" page.",
    "05034098": "The device cannot detect AMS D. Please reconnect the AMS cable or restart the printer.",
    "05804096": "The device cannot detect AMS-HT A. Please reconnect the AMS-HT cable or restart the printer.",
    "0583409C": "The firmware of AMS-HT D does not match the printer; the device cannot continue working. Please upgrade it on the \"Firmware\" page.",
    "0501409D": "The firmware of AMS B does not match the printer; the device cannot continue working. Please upgrade it on the \"Firmware\" page.",
    "18018006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS-HT PTFE tube is connected.",
    "18008006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS-HT PTFE tube is connected.",
    "07048006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "07078006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "07058006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "18078006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS-HT PTFE tube is connected.",
    "07008006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "18028006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS-HT PTFE tube is connected.",
    "18048006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS-HT PTFE tube is connected.",
    "07038006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "18058006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS-HT PTFE tube is connected.",
    "18038006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS-HT PTFE tube is connected.",
    "07018006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "07028006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "18068006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS-HT PTFE tube is connected.",
    "07068006": "Unable to feed filament into the extruder. This could be due to an entangled filament or a stuck spool. If not, please check if the AMS PTFE tube is connected.",
    "0502400C": "",
    "05024009": "",
    "0502400B": "",
    "0502400D": "Failed to start a new task: filament loading/unloading not completed.",
    "05024008": "",
    "0502400A": "",
    "05024007": "",
    "03004014": "Homing Z axis failed: temperature control abnormality.",
    "05004012": "The device is printing and cannot be upgraded at the moment. Please try again later.",
    "05004013": "AMS is in operation and cannot be upgraded at the moment. Please try again when it is idle.",
    "05004030": "The device is currently upgrading. Please try again when it is idle.",
    "0500400F": "AMS is initializing and cannot be upgraded at the moment. Please try again later.",
    "05004010": "AMS is drying and cannot be upgraded at the moment. Please try again later.",
    "05004011": "The printer is loading or unloading filament and cannot be upgraded at the moment. Please try again later.",
    "058440A2": "AMS-HT E communication is abnormal. Please reconnect the module cable or restart the printer.",
    "058640A2": "AMS-HT G communication is abnormal. Please reconnect the module cable or restart the printer.",
    "058540A2": "AMS-HT F communication is abnormal. Please reconnect the module cable or restart the printer.",
    "058240A2": "AMS-HT C communication is abnormal. Please reconnect the module cable or restart the printer.",
    "058740A2": "AMS-HT H communication is abnormal. Please reconnect the module cable or restart the printer.",
    "050240A3": "AMS(or AMS Lite) C communication is abnormal. Please reconnect the module cable or restart the printer.",
    "050140A3": "AMS(or AMS Lite) B communication is abnormal. Please reconnect the module cable or restart the printer.",
    "050040A3": "AMS(or AMS Lite) A communication is abnormal. Please reconnect the module cable or restart the printer.",
    "050340A3": "AMS(or AMS Lite) D communication is abnormal. Please reconnect the module cable or restart the printer.",
    "058140A2": "AMS-HT B communication is abnormal. Please reconnect the module cable or restart the printer.",
    "058040A2": "AMS-HT A communication is abnormal. Please reconnect the module cable or restart the printer.",
    "058340A2": "AMS-HT D communication is abnormal. Please reconnect the module cable or restart the printer.",
    "05008041": "The filament in hotend is too cold. Extrusion may damage the extruder. Still feeding in/out the filament?",
    "05008040": "Toolhead front cover is detached. Moving the toolhead may damage the printer. Do you want to continue?",
    "0502C014": "The AMS Remaining Filament Estimation is enabled by default and cannot be disabled.",
    "0500803C": "The current nozzle setting does not match the slicing file. Continuing to print may affect print quality. It is recommended to re-slice before starting the print.",
    "0502C024": "The flow dynamic calibration records have exceeded the storage limit. Please delete some historical records in the slicer software before adding new calibration data.",
    "0500403C": "The current nozzle setting does not match the slicing file. Continuing to print may affect print quality. It is recommended to re-slice before starting the print.",
    "0502C026": "The device is busy with the current task and cannot perform this operation for now. Please try again later.",
    "05004057": "The filament selected in the slicer requires a harder nozzle. Please replace the nozzle or adjust the filament settings before reprinting.",
    "05024027": "The current AMS does not support drying while printing. Please connect to the network and update the AMS firmware on the “Firmware” page.",
    "0500C04F": "The AMS is drying and cannot perform this operation at the moment.",
    "0500C04D": "The device is currently in laser or cutting mode and cannot start drying. Please do not initiate the drying process.",
    "0500C04B": "Filament in AMS outlet, the high drying temperature may cause AMS blockage. Drying cannot be started. Please unload the filament first.",
    "0500C04C": "The AMS is currently drying. Please do not start the process again.",
    "0500C04A": "AMS is calibrating, reading RFID or loading/unloading material, unable to initiate drying process, please wait.",
    "0500C04E": "Please connect a power adapter to the AMS-HT before starting the drying process.",
    "05004095": "No print plate detected. Please place it correctly and recalibrate.",
    "0502C028": "The filament currently loaded in the extruder does not support manual feeding.",
    "050040C0": "Communication error detected with AMS, AMS Lite or AMS HT. Please reconnect the module cable or restart the printer when it is idle.",
    "05008057": "The filament hardness selected in the slicer exceeds the current nozzle hardness. Continuing the print may cause nozzle wear, leading to leakage and unstable flow. Please proceed with caution.",
    "050040A6": "File download failed due to missing certificates. Please check the Fleet Hub certificate configuration and restart the printer before trying again",
}