# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Proto

class MessagePriority(object):
    Critical = 1
    High = 5
    Normal = 10
    Low = 15
    Background = 20

