# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Proto

class MessageContext(object):
    NONE = 0
    HandshakeSyn = 1
    HandshakeAck = 2
    WebStreamMsg = 3
    OctoNotification = 4
    OctoSummon = 5

