# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Proto

import octoflatbuffers
class OctoNotification(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = octoflatbuffers.encode.Get(octoflatbuffers.packer.uoffset, buf, offset)
        x = OctoNotification()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOctoNotification(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OctoNotification
    def Init(self, buf, pos):
        self._tab = octoflatbuffers.table.Table(buf, pos)

    # OctoNotification
    def Title(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # OctoNotification
    def Text(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # OctoNotification
    def Type(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(octoflatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # OctoNotification
    def ActionText(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # OctoNotification
    def ActionLink(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # OctoNotification
    def ShowForSec(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(octoflatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 5

    # OctoNotification
    def ShowOnlyIfLoadedFromOe(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(octoflatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

def Start(builder): builder.StartObject(8)
def OctoNotificationStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddTitle(builder, title): builder.PrependUOffsetTRelativeSlot(0, octoflatbuffers.number_types.UOffsetTFlags.py_type(title), 0)
def OctoNotificationAddTitle(builder, title):
    """This method is deprecated. Please switch to AddTitle."""
    return AddTitle(builder, title)
def AddText(builder, text): builder.PrependUOffsetTRelativeSlot(1, octoflatbuffers.number_types.UOffsetTFlags.py_type(text), 0)
def OctoNotificationAddText(builder, text):
    """This method is deprecated. Please switch to AddText."""
    return AddText(builder, text)
def AddType(builder, type): builder.PrependInt8Slot(2, type, 0)
def OctoNotificationAddType(builder, type):
    """This method is deprecated. Please switch to AddType."""
    return AddType(builder, type)
def AddActionText(builder, actionText): builder.PrependUOffsetTRelativeSlot(4, octoflatbuffers.number_types.UOffsetTFlags.py_type(actionText), 0)
def OctoNotificationAddActionText(builder, actionText):
    """This method is deprecated. Please switch to AddActionText."""
    return AddActionText(builder, actionText)
def AddActionLink(builder, actionLink): builder.PrependUOffsetTRelativeSlot(5, octoflatbuffers.number_types.UOffsetTFlags.py_type(actionLink), 0)
def OctoNotificationAddActionLink(builder, actionLink):
    """This method is deprecated. Please switch to AddActionLink."""
    return AddActionLink(builder, actionLink)
def AddShowForSec(builder, showForSec): builder.PrependUint32Slot(6, showForSec, 5)
def OctoNotificationAddShowForSec(builder, showForSec):
    """This method is deprecated. Please switch to AddShowForSec."""
    return AddShowForSec(builder, showForSec)
def AddShowOnlyIfLoadedFromOe(builder, showOnlyIfLoadedFromOe): builder.PrependBoolSlot(7, showOnlyIfLoadedFromOe, 1)
def OctoNotificationAddShowOnlyIfLoadedFromOe(builder, showOnlyIfLoadedFromOe):
    """This method is deprecated. Please switch to AddShowOnlyIfLoadedFromOe."""
    return AddShowOnlyIfLoadedFromOe(builder, showOnlyIfLoadedFromOe)
def End(builder): return builder.EndObject()
def OctoNotificationEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)