# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Proto

import octoflatbuffers
class OctoStreamMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = octoflatbuffers.encode.Get(octoflatbuffers.packer.uoffset, buf, offset)
        x = OctoStreamMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOctoStreamMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OctoStreamMessage
    def Init(self, buf, pos):
        self._tab = octoflatbuffers.table.Table(buf, pos)

    # OctoStreamMessage
    def ContextType(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(octoflatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # OctoStreamMessage
    def Context(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from octoflatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def Start(builder): builder.StartObject(2)
def OctoStreamMessageStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddContextType(builder, contextType): builder.PrependUint8Slot(0, contextType, 0)
def OctoStreamMessageAddContextType(builder, contextType):
    """This method is deprecated. Please switch to AddContextType."""
    return AddContextType(builder, contextType)
def AddContext(builder, context): builder.PrependUOffsetTRelativeSlot(1, octoflatbuffers.number_types.UOffsetTFlags.py_type(context), 0)
def OctoStreamMessageAddContext(builder, context):
    """This method is deprecated. Please switch to AddContext."""
    return AddContext(builder, context)
def End(builder): return builder.EndObject()
def OctoStreamMessageEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)