# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Proto

class OsType(object):
    Unknown = 0
    Debian = 1
    Windows = 2
    CrealitySonicPad = 3
    CrealityK1 = 4

