# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Proto

import octoflatbuffers
from typing import Any
from typing import Optional
class Property(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = octoflatbuffers.encode.Get(octoflatbuffers.packer.uoffset, buf, offset)
        x = Property()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProperty(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Property
    def Init(self, buf: bytes, pos: int):
        self._tab = octoflatbuffers.table.Table(buf, pos)

    # Property
    def Key(self) -> Optional[str]:
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Property
    def StrValue(self) -> Optional[str]:
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Property
    def IntValue(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(octoflatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Property
    def BoolValue(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(octoflatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def PropertyStart(builder: octoflatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: octoflatbuffers.Builder):
    PropertyStart(builder)

def PropertyAddKey(builder: octoflatbuffers.Builder, key: int):
    builder.PrependUOffsetTRelativeSlot(0, octoflatbuffers.number_types.UOffsetTFlags.py_type(key), 0)

def AddKey(builder: octoflatbuffers.Builder, key: int):
    PropertyAddKey(builder, key)

def PropertyAddStrValue(builder: octoflatbuffers.Builder, strValue: int):
    builder.PrependUOffsetTRelativeSlot(1, octoflatbuffers.number_types.UOffsetTFlags.py_type(strValue), 0)

def AddStrValue(builder: octoflatbuffers.Builder, strValue: int):
    PropertyAddStrValue(builder, strValue)

def PropertyAddIntValue(builder: octoflatbuffers.Builder, intValue: int):
    builder.PrependInt32Slot(2, intValue, 0)

def AddIntValue(builder: octoflatbuffers.Builder, intValue: int):
    PropertyAddIntValue(builder, intValue)

def PropertyAddBoolValue(builder: octoflatbuffers.Builder, boolValue: bool):
    builder.PrependBoolSlot(3, boolValue, 0)

def AddBoolValue(builder: octoflatbuffers.Builder, boolValue: bool):
    PropertyAddBoolValue(builder, boolValue)

def PropertyEnd(builder: octoflatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: octoflatbuffers.Builder) -> int:
    return PropertyEnd(builder)
