# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Proto

import octoflatbuffers
from octoflatbuffers.compat import import_numpy
np = import_numpy()

class OctoNotification(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = octoflatbuffers.encode.Get(octoflatbuffers.packer.uoffset, buf, offset)
        x = OctoNotification()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOctoNotification(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OctoNotification
    def Init(self, buf, pos):
        self._tab = octoflatbuffers.table.Table(buf, pos)

    # OctoNotification
    def Title(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # OctoNotification
    def Text(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # OctoNotification
    def Type(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(octoflatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # OctoNotification
    def AutoHide(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(octoflatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def Start(builder): builder.StartObject(4)
def OctoNotificationStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddTitle(builder, title): builder.PrependUOffsetTRelativeSlot(0, octoflatbuffers.number_types.UOffsetTFlags.py_type(title), 0)
def OctoNotificationAddTitle(builder, title):
    """This method is deprecated. Please switch to AddTitle."""
    return AddTitle(builder, title)
def AddText(builder, text): builder.PrependUOffsetTRelativeSlot(1, octoflatbuffers.number_types.UOffsetTFlags.py_type(text), 0)
def OctoNotificationAddText(builder, text):
    """This method is deprecated. Please switch to AddText."""
    return AddText(builder, text)
def AddType(builder, type): builder.PrependInt8Slot(2, type, 0)
def OctoNotificationAddType(builder, type):
    """This method is deprecated. Please switch to AddType."""
    return AddType(builder, type)
def AddAutoHide(builder, autoHide): builder.PrependBoolSlot(3, autoHide, 0)
def OctoNotificationAddAutoHide(builder, autoHide):
    """This method is deprecated. Please switch to AddAutoHide."""
    return AddAutoHide(builder, autoHide)
def End(builder): return builder.EndObject()
def OctoNotificationEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)